### ISSUE TITLE
Develop real-time ride status notifications for users, including alerts for driver arrivals and delays.

### ISSUE THREAD

**Issue by sushilbnk** [sushilbnk/RideOnWay#104]
Establish a system that provides users with real-time notifications regarding the status of their ride. These notifications should include alerts for when the driver arrives and any delays that may occur during the journey, ensuring users are informed throughout the process.

#6, belongs to sprint 3

**Comment by VigneshNallamothu** [comment]
Implemented real-time ride notifications, including alerts for driver arrivals and delays, to keep users informed throughout their journey.
