### ISSUE TITLE
Implement email alerts for web users to ensure timely updates.

### ISSUE THREAD

**Issue by sushilbnk** [sushilbnk/RideOnWay#105]
Set up a feature that sends email notifications to web users, ensuring they receive timely updates regarding their rides. This ensures users are informed of any changes or important information related to their journey.

#6, belongs to sprint 3

**Comment by sindhureddykandada** [comment]
Implemented a feature that sent email notifications to web users, ensuring they received timely updates regarding their rides. This ensured users were informed of any changes or important information related to their journey.
