### ISSUE TITLE
Create API endpoint to update ride status in the database.

### ISSUE THREAD

**Issue by sushilbnk** [sushilbnk/RideOnWay#84]
Create an API endpoint that receives ride status updates and updates the corresponding record in the database, facilitating real-time tracking of ride statuses.

#6, belongs to sprint 3

**Comment by kanjarlamanvitharao** [comment]
Develop an API endpoint that accepts ride status updates and synchronizes the corresponding database record, enabling real-time tracking of ride statuses.

**Comment by sushilbnk** [comment]
Developed an API endpoint that accepts ride status updates and synchronizes the corresponding database record, enabling real-time tracking of ride statuses.
