### ISSUE TITLE
Style the filtered ride list with CSS.

### ISSUE THREAD

**Issue by sushilbnk** [sushilbnk/RideOnWay#96]
Style the filtered ride list using CSS to enhance its visual appeal and usability, ensuring a pleasant and intuitive browsing experience for users.

#7, belongs to sprint 3

**Comment by Bhagya-Ramineni** [comment]
The filtered ride list had CSS styling applied to improve its visual appeal and usability, resulting in a pleasant and intuitive browsing experience for users.
