### ISSUE TITLE
Add a "No results found" message for empty search results.

### ISSUE THREAD

**Issue by sushilbnk** [sushilbnk/RideOnWay#97]
Include a "No results found" message in the filtered ride list component to provide users with feedback when their search query returns no matching rides.

#7, belongs to sprint 3

**Comment by Bhagya-Ramineni** [comment]
Incorporate a "No results found" message within the filtered ride list component to offer users feedback when their search query yields no matching rides.

**Comment by Bhagya-Ramineni** [comment]
added "No results found" message within the filtered ride list component to offer users feedback when their search query yields no matching rides.
